apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: "apacheserver"
        image: fchapuzot/customhttpd:2.4
        imagePullPolicy: Always
        env:
        - name: SERVER_MESSAGE
          value: BaseMessage
        ports:
        -  name: server-endpoint
           containerPort: 8000
