apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: "apacheserver"
        env:
        - name: SERVER_MESSAGE
          value: Instance4
